CREATE TABLE CUSTOMERS (
	CUST_ID CHAR(5 OCTETS) NOT NULL, 
	CUSTNAME CHAR(20 OCTETS) NOT NULL, 
	ADDRESS1 VARCHAR(100 OCTETS) NOT NULL, 
	ADDRESS2 VARCHAR(100 OCTETS), 
	LOCALITY VARCHAR(56 OCTETS), 
	CITY VARCHAR(60 OCTETS), 
	STATE VARCHAR(30 OCTETS), 
	COUNTRY_CODE CHAR(2 OCTETS), 
	POSTAL_CODE VARCHAR(15 OCTETS), 
	POSTAL_CODE_PLUS4 CHAR(4 OCTETS), 
	EMAIL_ADDRESS VARCHAR(70 OCTETS), 
	PHONE_NUMBER VARCHAR(20 OCTETS), 
	YTD_SALES DECIMAL(7 , 2) NOT NULL DEFAULT 0.0, 
	SALESMAN_ID CHAR(6 OCTETS), 
	NATIONALITY VARCHAR(30 OCTETS), 
	NATIONAL_ID VARCHAR(30 OCTETS), 
	CREDITCARD_NUMBER VARCHAR(19 OCTETS), 
	CREDITCARD_TYPE VARCHAR(30 OCTETS), 
	CREDITCARD_EXP CHAR(4 OCTETS), 
	CREDITCARD_CVV VARCHAR(4 OCTETS), 
	DRIVER_LICENSE VARCHAR(30 OCTETS)
	);
CREATE TABLE SALES (
	SALESMAN_ID CHAR(6 OCTETS) NOT NULL, 
	FIRST_NAME VARCHAR(15 OCTETS) NOT NULL, 
	LAST_NAME VARCHAR(15 OCTETS) NOT NULL, 
	NATIONALITY VARCHAR(30 OCTETS), 
	NATIONAL_ID VARCHAR(30 OCTETS), 
	PHONE_NUMBER VARCHAR(20 OCTETS) NOT NULL, 
	AGE SMALLINT NOT NULL DEFAULT 0, 
	SEX CHAR(1 OCTETS) NOT NULL DEFAULT ' ', 
	TERRITORY VARCHAR(14 OCTETS) NOT NULL, 
	EMAIL_ADDRESS VARCHAR(70 OCTETS) NOT NULL, 
	MANAGER_ID VARCHAR(6 OCTETS)
	);
CREATE TABLE ORDERS (
	ORDER_ID SMALLINT NOT NULL, 
	CUST_ID CHAR(5 OCTETS) NOT NULL, 
	ORDER_DATE TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
	ORDER_TIME TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
	FREIGHT_CHARGES DECIMAL(4 , 2), 
	ORDER_SALESMAN CHAR(6 OCTETS), 
	ORDER_POSTED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
	ORDER_SHIP_DATE CHAR(8 OCTETS) DEFAULT NULL
	);